### ISSUE TITLE
Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by boynedmaster** [expressjs/session#145]
```
N:\MyBGO\Server\node_modules\express-session\index.js:151
    if (req.session) return next();
           ^
TypeError: Cannot read property 'session' of undefined
    at session (N:\MyBGO\Server\node_modules\express-session\index.js:151:12)
    at Object.<anonymous> (N:\MyBGO\Server\mybgo.js:68:11)
    at Object.<anonymous> (N:\MyBGO\Server\mybgo.js:98:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by dougwilson** [comment]
Can you paste what you have on line 68 in the file `N:\MyBGO\Server\mybgo.js`?

**Comment by boynedmaster** [comment]
(This is compiled CoffeeScript, by the way)
(Also the error line changed apparently, Line 53 now)
app.use(session());

(Also the variables that relate to this)
expressSession = require("express-session");
session = expressSession({
    secret: "mysecret",
    key: "mybho.sid",
    resave: true,
    saveUninitialized: true,
    store: new mysql_store(mysql_options)
  });

**Comment by dougwilson** [comment]
Your

    app.use(session());

Needs to be

    app.use(session);
