### ISSUE TITLE
set 'req.session.cookie.expires' to 'false' ?

### ISSUE THREAD

**Issue by matanshukry** [expressjs/session#183]
The documentation (README) says I can set `req.session.cookie.expires` to `false`. However, when setting it (right before calling .login() and .redirect() after login). The relevant code of mine is:

```
if (req.body.remember !== "on") {
    req.session.cookie.expires = false;
}
```

the error is:
```
undefined is not a function - TypeError: undefined is not a function
    at Object.serialize (node_modules\express-session\node_modules\cookie\index.js:95:56)
    at setcookie (node_modules\express-session\index.js:577:21)
    at ServerResponse.<anonymous> (node_modules\express-session\index.js:200:7)
    at ServerResponse.writeHead (node_modules\express-session\node_modules\on-headers\index.js:44:16)
    at ServerResponse._implicitHeader (_http_server.js:172:8)
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:423:10)
    at writetop (node_modules\express-session\index.js:248:26)
    at ServerResponse.end (node_modules\express-session\index.js:293:16)
    at ServerResponse.redirect (node_modules\express\lib\response.js:900:10)
...
```

Reading cookie\index.js file at line 95 shows the problem:

`if (opt.expires) pairs.push('Expires=' + opt.expires.toUTCString());`

the line clearly calls toUTCString() function, which only exists for Date, and not boolean (false value).

Am I missing something? Is there perhaps a specific place I am allowed to call this, and not everywhere?
Also, I'm using version 1.11.3

**Comment by matanshukry** [comment]
I was to quick to say;
It seems using a persistent session stores everything, including non-wanted values.
I started by using 'true' (mistakenly), and after changing it to 'false', it kept reading true from the session store, generating error, and never reaching false.

My apologies
