### ISSUE TITLE
can't use express-session

### ISSUE THREAD

**Issue by juniorkid** [expressjs/session#207]
bright@ubuntu:~/Desktop/Project/webserver$ node nodeTest.js 
module.js:338
    throw err;
          ^
Error: Cannot find module 'cookie'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bright/Desktop/Project/webserver/node_modules/express-session/index.js:14:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by juniorkid** [comment]
How can solve it ?
Thank you

**Comment by gabeio** [comment]
It seems like you didn't installed `express-session` with npm or npm did not install the dependencies of `express-session` which yes is a library called `cookie`. Inside your folder there (`~/Desktop/Project/webserver`) try running `npm install express-session` and then try running that file again.

**Comment by juniorkid** [comment]
i installed it but it can't use and have same problem.

**Comment by juniorkid** [comment]
i run it on ubuntu 10.04 LTS

**Comment by dougwilson** [comment]
Unfortunately this is beyond our help ability. You may want to file a support request on https://github.com/npm/npm/

My only other advice is to remove your `express-session` install, clear your `npm` cache, and try re-installing:
```
$ rm -rf node_modules/express-session
$ npm cache clean
$ npm i express-session
```

**Comment by juniorkid** [comment]
i will try it.

**Comment by juniorkid** [comment]
I can run it. Thank you very much.

**Comment by asifzcpe** [comment]
I faced the same problem in express version >4 .
The way I solved it:
just add `"express-session": "^1.7.6"` in package.json file and run `npm install `command and it installed and worked fine
