### ISSUE TITLE
Problem with redis session store and regenerate

### ISSUE THREAD

**Issue by pjacferreira** [expressjs/session#310]
Hi, 

In a recent project I had a problem, win which I'm using expressj/express-session/redis as session store I had a problem.

I needed to destroy an existing session and start a new, in the same request. 

the only solution I found was to use:
request.session.regenerate();

Unfortunately this generated an error when responding to the request:

```
/home/user/Projects/erp/services/node_modules/express-session/session/store.js:43
    fn(err);
    ^

TypeError: fn is not a function
    at Command.callback (/home/user/Projects/erp/services/node_modules/express-session/session/store.js:43:5)
    at normal_reply (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/index.js:662:21)
    at RedisClient.return_reply (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/index.js:722:9)
    at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/index.js:14
6:18)
    at JavascriptReplyParser.run (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/node_modules/redis-parser/lib/javascript.js:137:18)
    at JavascriptReplyParser.execute (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/node_modules/redis-parser/lib/javascript.js:112
:10)
    at Socket.<anonymous> (/home/user/Projects/erp/services/node_modules/connect-redis/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

    at readableAddChunk (_stream_readable.js:146:16)
``` 

The trace points to (store.js - line 43):

```js
Store.prototype.regenerate = function(req, fn){
  var self = this;
  this.destroy(req.sessionID, function(err){
    self.generate(req);
    fn(err); /**** PROBLEM ****/
  });
};
```

I looked at the calling function:
```js
function normal_reply (self, reply, command_obj) {
    if (typeof command_obj.callback === 'function') {
        if ('exec' !== command_obj.command) {
            reply = self.handle_reply(reply, command_obj.command, command_obj.buffer_args);
        }
        command_obj.callback(null, reply); /*** SOURCE ***/
    } else {
        debug('No callback for reply');
    }
}
```

I noticed that 'fn' is always undefined!?

Is this expected.

**Comment by dougwilson** [comment]
Hi @pjacferreira, the error you posted is because of your code calling `request.session.regenerate();`. You see, you *must* supply a callback function to the `.regenerate` method. If you code is `request.session.regenerate();` this is incorrect. You code needs to be the following:
```js
request.session.regenerate(function (err) {
  // handle err
  // proceed with other logic populating the new session
});
```

I hope that helps!

**Comment by dougwilson** [comment]
Of course, an additional bit of information here is that the session store you are using, `connect-redis` in this case, is what dictates if the callback is required. The `connect-redis` module requires you provide the callback, and it also does not provide an early catch if you missed it. You may want to file an issue over at `connect-redis` regarding that.

**Comment by pjacferreira** [comment]
@dougwilson Thank you for the information,
