### ISSUE TITLE
Getting "Cannot read property 'connect.sid' " after setting app.use(session({ ... }))

### ISSUE THREAD

**Issue by andrejkaurin** [expressjs/session#339]
```
var session = require('express-session');
app.use(session({
    secret: 'keyboard cat',
    cookie: { }
}));
```

After that is executed I am getting the following error

```
500:  [TypeError: Cannot read property 'connect.sid' of undefined]
500:  [TypeError: Cannot read property 'connect.sid' of undefined]
TypeError: Cannot read property 'connect.sid' of undefined
    at session (/Users/andrejkaurin/LCMA/node_modules/express-session/index.js:115:32)
    at Layer.handle [as handle_request] (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:270:13)
    at /Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:237:9
    at Function.proto.process_params (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:312:12)
    at /Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:189:10)
    at expressInit (/Users/andrejkaurin/LCMA/node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:270:13)
    at /Users/andrejkaurin/LCMA/node_modules/express/lib/router/index.js:237:9
```

**Comment by dougwilson** [comment]
Weird. I see from your stack trace that the error is coming from line 115, which in the current version (1.14.0) is blank: https://github.com/expressjs/session/blob/v1.14.0/index.js#L115

What version of this module are you using? Can you provide full code I can run that reproduces the issue (please include the steps I need to perform to reproduce the error).

**Comment by andrejkaurin** [comment]
"version": "1.0.4",

**Comment by dougwilson** [comment]
There is no way I'm really going to be able to support such an old version. Can you try upgrading? See if your bug has been resolved at some point.

**Comment by dougwilson** [comment]
I took a quick look and the reason you have having that issue is because back in that old version, you need to use the `cookie-parser` middleware before this middleware. It wasn't until version 1.5.0 that you could stop using that other middleware. Please refer to the `README.md` file that is part of your on-disk install for the documentation that is relevant to the version of this module you have installed :)!

**Comment by andrejkaurin** [comment]
OK I got it now. Upgraded to 1.14.0 and it works now.
Thanks.

**Comment by olayemiabdul** [comment]
Upgrade the package by npm install express-session to install the latest verrsion
