### ISSUE TITLE
Incorrectly attempting to use a repl set?

### ISSUE THREAD

**Issue by joeyfigaro** [expressjs/session#373]
Using in combination with Mongoose - looks like mongoose, express-session, or connect-mongo is trying to use a repl set with a connection string that has no params? Our production builds are blowing up with the following: 

``` shell
Error: Cannot write to a secondary
    at canCheckoutWriter (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:730:13)
    at Server.checkoutWriter (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:752:16)
    at Collection.update (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:651:63)
    at /var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:340:18
    at MongoStore.getCollection (/var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:210:11)
    at MongoStore.set (/var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:338:10)
    at Session.save (/var/local/www/node_modules/express-session/session/session.js:63:25)
    at ServerResponse.res.end (/var/local/www/node_modules/express-session/index.js:194:28)
    at Array.write (/var/local/www/node_modules/express/node_modules/finalhandler/index.js:126:9)
^C    at listener (/var/local/www/node_modules/express/node_modules/on-finished/index.js:164:15)
    at onFinish (/var/local/www/node_modules/express/node_modules/on-finished/index.js:95:5)
    at callback (/var/local/www/node_modules/express/node_modules/on-finished/node_modules/ee-first/index
```

session setup:

``` js
app.use(session({
        secret: process.env.SESSION_SECRET || config.keys.session.secret,
        key: process.env.SESSION_IDENTIFIER || config.keys.session.identifier,
        proxy: true,
        store: new store({ mongooseConnection: app.get('connection') }),
        resave: true,
        saveUninitialized: true
    }));
```

...and where we're setting up the connection:

``` js
const DB_URL = process.env.DB_URL || config.database.dev.url;
app.set('connection', mongoose.createConnection(DB_URL));
```

**Comment by JoeWagner** [comment]
Hi @joeyfigaro 
I don't notice anything based on the info you've given, but it seems unlikely it is related to this module.
From your description it seems like an issue with your Mongo connection string. 
A couple of thing I would try, based on issues I've had in the past:

 - Does your Mongo URI have at least two seeds?  Sounds like you are trying to connect to a repl set, which would require you to include at least two seeds as per the [docs](https://docs.mongodb.com/manual/reference/connection-string/#urioption.replicaSet)

 - Alternatively, I've had issues in the past where Mongoose and my store were using different versions of the Node MongoDB Driver.  Maybe check that out as well

**Comment by dougwilson** [comment]
I'm going to close this, as I think it was answered, mainly in that this module really has no insight into what your store is actually doing, at it would at least be a bug in that store if anything.
