### ISSUE TITLE
Cannot regenerate session

### ISSUE THREAD

**Issue by yannik-b** [expressjs/session#379]
```
/home/[...]/node_modules/express-session/session/store.js:54
    fn(err);
    ^

TypeError: fn is not a function
    at Immediate.<anonymous> (/home/[...]/node_modules/express-session/session/store.js:54:5)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

This failure is only present when I try to regenerate a session.

**Comment by dougwilson** [comment]
That error looks like you didn't pass in a calback to the regenerate method (docs: https://github.com/expressjs/session#sessionregenerate).

**Comment by yannik-b** [comment]
Thanks, I have changed session.destroy to session.regenerate, so I thought destroy needs no callback, so regenerate don't need one too.
