### ISSUE TITLE
Warning: a promise was created in a handler (with possible fix)

### ISSUE THREAD

**Issue by nstuyvesant** [expressjs/session#501]
Getting this warning...
```
(node:65902) Warning: a promise was created in a handler at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/nates/dev/shy/node_modules/bluebird/js/release/method.js:29:9)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Function.findAll (/Users/nates/dev/shy/node_modules/sequelize/lib/model.js:1495:23)
    at index (/Users/nates/dev/shy/server/api/schedule/schedule.controller.js:19:19)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at checkCsrf (/Users/nates/dev/shy/node_modules/lusca/lib/csrf.js:95:20)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at hsts (/Users/nates/dev/shy/node_modules/lusca/lib/hsts.js:25:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at xframe (/Users/nates/dev/shy/node_modules/lusca/lib/xframes.js:12:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at xssProtection (/Users/nates/dev/shy/node_modules/lusca/lib/xssprotection.js:16:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at lusca (/Users/nates/dev/shy/node_modules/lusca/index.js:63:9)
From previous event:
    at E4Store.get (/Users/nates/dev/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12)
    at session (/Users/nates/dev/shy/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/nates/dev/shy/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/nates/dev/shy/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/Users/nates/dev/shy/node_modules/method-override/index.js:65:14)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Users/nates/dev/shy/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
GET /api/schedule 304 47.378 ms - -
(node:65902) Warning: a promise was created in a handler at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/nates/dev/shy/node_modules/bluebird/js/release/method.js:29:9)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Function.findAll (/Users/nates/dev/shy/node_modules/sequelize/lib/model.js:1495:23)
    at index (/Users/nates/dev/shy/server/api/announcement/announcement.controller.js:19:23)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at checkCsrf (/Users/nates/dev/shy/node_modules/lusca/lib/csrf.js:95:20)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at hsts (/Users/nates/dev/shy/node_modules/lusca/lib/hsts.js:25:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at xframe (/Users/nates/dev/shy/node_modules/lusca/lib/xframes.js:12:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at xssProtection (/Users/nates/dev/shy/node_modules/lusca/lib/xssprotection.js:16:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:59:28
    at lusca (/Users/nates/dev/shy/node_modules/lusca/index.js:63:9)
From previous event:
    at E4Store.get (/Users/nates/dev/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12)
    at session (/Users/nates/dev/shy/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/nates/dev/shy/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/nates/dev/shy/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/Users/nates/dev/shy/node_modules/method-override/index.js:65:14)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Users/nates/dev/shy/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
```

When I add
`return null;`
after this [line](https://github.com/expressjs/session/blob/master/index.js#L489), the warning goes away.

Any thoughts on why this is happening?

Thanks,
Nate

**Comment by dougwilson** [comment]
Nothing in this module uses promises, so not sure.  Can you explain exactly how that change fixes the issue? Would all return statements need that change or only the one and why?

**Comment by dougwilson** [comment]
Reading around online for this warning and express,  it seems like the root fix should be in your own code. Can you provide the following?

1. Version of Node.js
2. Version of this module
3. Complete code I can run to reproduce this warning.
4. Complete instructions to run your code and see warning. 

Thanks!

**Comment by nstuyvesant** [comment]
Node.js 8.3.0, express-session 1.15.5, express 4.15.4, express-sequelize-session 0.4.0. My project was built from generator-angular-fullstack 4.2.2 and I've seen that others are running into the same problem.

Trying to build a smaller example to reproduce. My full project is at https://github.com/nstuyvesant/shy. When the project is started using gulp serve, the warning seems to be related to express-sequelize-session (which uses a promise) calling express-session.

E4Store.get (/Users/nates/dev/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12) is the .then() line below...
```
      E4Store.prototype.get = function(sid, callback) {
        return this.Session.findOne({
          where: {
            sid: sid
          },
          attributes: ['data']
        }).then(function(session) {
          if (session != null) {
            return typeof callback === "function" ? callback(null, JSON.parse(session.data)) : void 0;
          } else {
            return typeof callback === "function" ? callback(null, null) : void 0;
          }
        })["catch"](function(err) {
          return typeof callback === "function" ? callback(err, null) : void 0;
        });
      };
```
The two paths within then() do a return but make a callback (more on this below).

Here's session (/Users/nates/dev/shy/node_modules/express-session/index.js:460:11)
```
    store.get(req.sessionID, function(err, sess){
      // error handling
      if (err) {
        debug('error %j', err);

        if (err.code !== 'ENOENT') {
          next(err);
          return;
        }

        generate();
      // no session
      } else if (!sess) {
        debug('no session found');
        generate();
      // populate req.session
      } else {
        debug('session found');
        store.createSession(req, sess);
        originalId = req.sessionID;
        originalHash = hash(sess);

        if (!resaveSession) {
          savedHash = originalHash
        }

        wrapmethods(req.session);
      }

      next(); // suppresses warning if changed to next(); return null;
    });
```

The rule is to always return a promise as to not accidentally be swallowing errors or returns. One awkward case when dealing with Express 4 is within a route context, as you want to start your chain with Promise.try() but at the same time you can't return this promise chain from the route (as it's a callback). This is usually the situation where we see this warning using express and what I suspect may be happening here in express-sequelize-session calling express-session.

Adding` return null;` below the `next();` in express-session suppresses the warning.

Do you think that the issue might be what's happening in express-sequelize-session above this?

**Comment by dougwilson** [comment]
> Addingreturn null; below the next(); in express-session suppresses the warning.

This is correct, but I think you may be misunderstanding it. This is about your code, not every middleware that exists needs to change. As in if you are using Bluebird and within a .then() or within a .catch() you cann next() you also need to return null from that function. The only reason changing middleware would make any difference is if you are writing return next(), which means you are at the mercy of to whatever next() is returning (which is always going to be meaningless).

**Comment by dougwilson** [comment]
P.S. I did try to run your app to reproduce, but wasn't ever able to actually get the dependencies installed:
```
$ git clone git@github.com:nstuyvesant/shy.git
Cloning into 'shy'...
remote: Counting objects: 8532, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 8532 (delta 12), reused 22 (delta 8), pack-reused 8493
Receiving objects: 100% (8532/8532), 27.75 MiB | 7.21 MiB/s, done.
Resolving deltas: 100% (6348/6348), done.

$ cd shy/

shy (master)$ npm i
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> sodium@2.0.1 preinstall shy/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at shy/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [libsodium] Error 1
shy/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (shy/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm WARN sinon-chai@2.12.0 requires a peer of sinon@^1.4.0 || ^2.1.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2017-08-13T15_09_39_650Z-debug.log
```

Let me know what I'm missing and I'd be happy to take a look at your specific app for the warning that is printed with grunt serve.

**Comment by dougwilson** [comment]
I had tried to run `gulp serve` even though there was an error installing, but that ended up with an error as well, not sure if it was related to the install failing:
```
shy (master)$ npx gulp serve
npx: installed 185 in 3.471s
[11:13:57] Requiring external module babel-register
[11:13:59] Using gulpfile shy/gulpfile.babel.js
[11:13:59] Starting 'serve'...
[11:13:59] Starting 'clean:tmp'...
[11:13:59] Starting 'lint:scripts'...
[11:13:59] Starting 'lint:scripts:client'...
[11:13:59] Starting 'lint:scripts:server'...
[11:13:59] Starting 'inject'...
[11:13:59] Starting 'inject:scss'...
[11:13:59] Starting 'copy:fonts:dev'...
[11:13:59] Starting 'env:all'...
[11:13:59] Finished 'env:all' after 1.12 ms
[11:13:59] Finished 'clean:tmp' after 242 ms
[11:14:00] gulp-inject 19 files into app.scss.
[11:14:00] Finished 'inject:scss' after 668 ms
[11:14:00] Finished 'inject' after 668 ms
[11:14:01] Finished 'copy:fonts:dev' after 1.44 s
[11:14:01] Finished 'lint:scripts:server' after 2.21 s
[11:14:02]
shy/client/components/usermanager/usermanager.component.js
  128:11  error  'attendance' is assigned a value but never used  no-unused-vars
  138:20  error  'attendance' is defined but never used           no-unused-vars

✖ 2 problems (2 errors, 0 warnings)

[11:14:02] Finished 'lint:scripts:client' after 2.69 s
[11:14:02] Finished 'lint:scripts' after 2.7 s
[11:14:02] Starting 'start:server'...
[11:14:02] Finished 'start:server' after 57 ms
[11:14:02] Starting 'start:client'...
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: shy/server/**/*
[nodemon] starting `node --trace-deprecation --trace-warnings server`
url.js:81
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at new Sequelize (node_modules/sequelize/lib/sequelize.js:110:28)
    at Object.<anonymous> (shy/server/sqldb/index.js:7:14)
    at Module._compile (module.js:570:32)
    at loader (shy/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (shy/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (shy/server/app.js:8:1)
    at Module._compile (module.js:570:32)
    at loader (shy/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (shy/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (shy/server/index.js:12:28)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by dougwilson** [comment]
Jut eye-balling through the code, I see where the underlying missing `return null` is into a `.then()` or `.catch()` that is calling a callback based on your provided stack trace, and there is already an open pull request to fix it: https://github.com/dgf/express-sequelize-session/pull/3

Does that pull request fix the issue for you (since I can't easily verify)?

**Comment by nstuyvesant** [comment]
Sorry about the install issues. I use node-sodium (libsodium) which has a dependency on libtool, autoconf, and automake (if you use macOS... brew install libtool autoconf automake).

But regarding [https://github.com/dgf/express-sequelize-session/pull/3](https://github.com/dgf/express-sequelize-session/pull/3), yeah, that should catch it.

**Comment by dougwilson** [comment]
It's no problem -- I'm running it in a Linux container where I run any code I randomly download from the Internet :) So yea, if that pull request works to suppress the warning, that's awesome! The code within their `.then()` call is calling the provided callback and returning whatever value the callback returns to the `.then()` call, which I suppose is why changing it downstream (here) is having an effect. Ideally that module should change every single `.then()` and `.catch()` to return some explicit value (like `null`) instead of returning whatever `callback()` is returning. This is only an issue when Bluebird is used; the native Promise implementation doesn't have this issue.

In our README we list at least two Sequelize store modules you can use (neither of which are that one) that shouldn't give you warnings when using them and are actively maintained.

**Comment by nstuyvesant** [comment]
Thanks - yeah, seems like that one is a bit dated and I agree the issue is in express-sequelize-session. I should probably suggest a change to generator-angular-fullstack to replace it with an alternative such as those listed in your read me others don't run into that.

Thanks again,
Nate
