### ISSUE TITLE
how to read from default session store?

### ISSUE THREAD

**Issue by VenPot** [expressjs/session#593]
I think this is more of a question than an issue

session.store.all is not returning the sessions. am i accessing it wrong? Here is my code
```js
var session = require('express-session');

app.use(function(req, res, next) {
  session.store.all(function(err, sessions) {
    console.log('sessions', sessions)
  })
}
```
**error message:**
```
TypeError: Cannot read property 'all' of undefined
    at Object.handle (/home/ubuntu/workspace/CTL/user.js:50:16)
    at next (/home/ubuntu/workspace/node_modules/connect/lib/proto.js:190:15)
    at SessionStrategy.strategy.pass (/home/ubuntu/workspace/CTL/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/home/ubuntu/workspace/CTL/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/home/ubuntu/workspace/CTL/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at Object.authenticate [as handle] (/home/ubuntu/workspace/CTL/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at next (/home/ubuntu/workspace/node_modules/connect/lib/proto.js:190:15)
    at Object.initialize [as handle] (/home/ubuntu/workspace/CTL/node_modules/passport/lib/middleware/initialize.js:53:5)
    at next (/home/ubuntu/workspace/node_modules/connect/lib/proto.js:190:15)
    at Immediate.<anonymous> (/home/ubuntu/workspace/CTL/node_modules/express-session/index.js:489:7)
```
i am trying to display the available sessions in the MemoryStore

**Comment by dougwilson** [comment]
You need to call `.all` on the actual store itself -- the `session` variable in your example is the `express-session` middleware factory which doesn't have a `.store` property. Here is a fuller example:
```js
var session = require('express-session');
var store = new session.MemoryStore();

app.use(session({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true,
  store: store
}));

app.use(function(req, res, next) {
  store.all(function(err, sessions) {
    console.log('sessions', sessions)
  })
}
```

**Comment by dougwilson** [comment]
You can access `req.sessionStore`
