### ISSUE TITLE
(node:18726) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version

### ISSUE THREAD

**Issue by saydulk** [expressjs/session#666]
![Screenshot from 2019-06-12 20-08-07](https://user-images.githubusercontent.com/1058663/59358233-03aac700-8d4e-11e9-9df5-0d9a9775026e.png)
warning ../../package.json: No license field
$ node app
(node:18726) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/home/username/DEX3/dex-back-end/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/username/DEX3/dex-back-end/app.js:152:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dougwilson** [comment]
Looks like the error is from mongo. You are likely using some kind of mongo store, which is where you'll want to report the issue :+1:
