### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.

### ISSUE THREAD

**Issue by webface** [expressjs/session#731]
I've been getting this error even though I have tried multiple database memory stores. I am deploying on docker and when i console log my api container I get the warning once tthe server starts up
```
# docker logs node-app-be

> admin-bro-file-upload@1.0.0 start /backend
> node server.js

Mon, 16 Mar 2020 22:25:53 GMT express-session deprecated undefined resave option; provide resave option at node_modules/admin-bro-expressjs/plugin.js:138:14
Mon, 16 Mar 2020 22:25:53 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:138:14
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
AdminBro: bundling user components...
Server running on port 3018
'useState' is imported from external module 'react' but never used
'BasePropertyProps' is imported from external module 'admin-bro' but never used
AdminBro: bundle ready
session Session {
  cookie: {
    path: '/',
    _expires: 2020-03-23T22:26:58.895Z,
    originalMaxAge: 604800000,
    httpOnly: true,
    secure: true
  }
}
```
All the google results suggested different db memory stores. I tried them all and I still get the warning.
Here is my server.js Please help>

```
const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const AdminBroExpress = require('admin-bro-expressjs');
const bcrypt = require('bcryptjs');
const session = require('express-session');
var MemoryStore = require('memorystore')(session)
const { getSecret } = require('./app/secrets');
const { adminBro } = require('./adminbro');



if (process.env.NODE_ENV !== 'production') {
	require('dotenv').config();
}

mongoose.Promise = global.Promise;
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);

const User = require('./app/models/user');
const installRoute = require('./app/routes/install');
const dataRoute =  require('./app/routes/data');

const app = express();
const port = process.env.PORT;


if (app.get('env') === 'production') {
  app.set('trust proxy', 1) // trust first proxy
}


const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
  authenticate: async (email, password) => {
    const user = await User.findOne({ email })
    if (user) {
      const matched = await bcrypt.compare(password, user.encryptedPassword)
      if (matched) {
        return user
      }
    }
    return false
  },
  cookiePassword: 'some-secret-password-used-to-secure-cookie',
})
app.use(session({
  name: 'session',
  secret: 'tranquility-bay',
  cookie: {
    maxAge: 1000 * 60 * 60 * 24 * 7, // 1 week
    secure: app.get('env') === 'production' ? true: false
  },
  store: new MemoryStore({
    checkPeriod: 86400000 // prune expired entries every 24h
  }),
  path: '/',
  resave: true,
  saveUninitialized: false
}));
app.use(cors());
app.options('*', cors());
app.set('view engine', 'ejs');
app.use(express.static('./public'));
app.use(adminBro.options.rootPath, router);
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use(function(req,res,next){
  if(!req.session){
      return next(new Error('Oh no')) //handle error
  }
  console.log('session', req.session)
  next() //otherwise continue
});

app.use('/', installRoute);
app.use('/data', dataRoute);

const run = async () => {
  await mongoose.connect(getSecret('dbUri'),
  { useNewUrlParser: true, useUnifiedTopology: true })
  app.listen(port, () => {
    console.log(`Server running on port ${port}`)
  })
}
run()
```

**Comment by dougwilson** [comment]
The reason you're not able to make the warning go away is because you are actually creating two different `express-session` instances in your example: one you are creating directly above, but a second one is being created by the `admin-bro-expressjs` module you are using, which is where the warning is coming from.
