### ISSUE TITLE
Error when adding req.session.regenerate();

### ISSUE THREAD

**Issue by Daxcor69** [expressjs/session#809]
```
/mnt/foundry_code/www2/node_modules/express-session/session/store.js:54
    fn(err);
    ^

TypeError: fn is not a function
    at Command.callback (/mnt/foundry_code/www2/node_modules/express-session/session/store.js:54:5)
    at normal_reply (/mnt/foundry_code/www2/node_modules/redis/index.js:654:21)
    at RedisClient.return_reply (/mnt/foundry_code/www2/node_modules/redis/index.js:752:9)
    at JavascriptRedisParser.returnReply (/mnt/foundry_code/www2/node_modules/redis/index.js:137:18)
    at JavascriptRedisParser.execute (/mnt/foundry_code/www2/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/mnt/foundry_code/www2/node_modules/redis/index.js:218:27)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[nodemon] app crashed - waiting for file changes before starting...
```
When I added  req.session.regenerate(); to my code. I already had a session active, I just wanted to do a regen. I am using a redis backend as a store.

When I add:
```
req.session.regenerate(function(err) {
  // will have a new session here
})
```
I don't get the error.

**Comment by dougwilson** [comment]
The error is because you didn't provide the callback to the method: https://github.com/expressjs/session#sessionregeneratecallback
