### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by 0zob** [expressjs/session#893]
Hi, I'm having a uncommon error like this issue [this issue](https://github.com/expressjs/session/issues/395).
I can't find where in my code this error trigger.

error:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Query.<anonymous> (/home/enzotorrs/source/globo/api-jack/node_modules/express-mysql-session/index.js:185:18)
    at Query.<anonymous> (/home/enzotorrs/source/globo/api-jack/node_modules/underscore/underscore-node-f.cjs:1213:19)
    at Query.<anonymous> (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/enzotorrs/source/globo/api-jack/node_modules/mysql/lib/protocol/Parser.js:433:10)

package.json
"dependencies": {
  11   │     "aws-sdk": "^2.1121.0",
  12   │     "axios": "^0.27.0",
  13   │     "base64-arraybuffer": "^1.0.2",
  14   │     "bcrypt": "^5.0.1",
  15   │     "body-parser": "~1.20.0",
  16   │     "compression": "^1.7.4",
  17   │     "config": "^3.3.7",
  18   │     "cookie-parser": "~1.4.6",
  19   │     "cors": "^2.8.5",
  20   │     "debug": "~4.3.4",
  21   │     "ejs": "~3.1.7",
  22   │     "elasticsearch": "^16.7.2",
  23   │     "express": "^4.18.0",
  24   │     "express-mysql-session": "^2.1.7",
  25   │     "express-session": "^1.17.2",
  26   │     "joi": "^17.6.0",
  27   │     "jsonwebtoken": "^8.5.1",
  28   │     "jwk-to-pem": "^2.0.5",
  29   │     "mimemessage": "^1.0.5",
  30   │     "mobile-detect": "^1.4.5",
  31   │     "moment-timezone": "^0.5.34",
  32   │     "morgan": "^1.10.0",
  33   │     "multer": "^1.4.4",
  34   │     "mysql": "^2.18.1",
  35   │     "mysql2": "^2.3.3",
  36   │     "node-xlsx": "^0.21.0",
  37   │     "passport": "^0.5.2",
  38   │     "passport-oauth2": "^1.6.1",
  39   │     "querystring": "^0.2.0",
  40   │     "ramda": "^0.28.0",
  41   │     "sequelize": "^6.19.0",
  42   │     "sequelize-auto-migrations": "^1.0.3",
  43   │     "sequelize-cli": "^6.4.1",
  44   │     "url": "^0.11.0",
  45   │     "uuid": "^8.3.2",
  46   │     "winston": "^3.7.2"

**Comment by dougwilson** [comment]
Hi @0zob sorry you are having an issue. Unfortunately the error is not coming from this module, but instead your store module. Your stack trace shows it is from here:

https://github.com/chill117/express-mysql-session/blob/dfa7207c188947cc2af685717825e4830b6c897f/index.js#L185

The error would indicate that somehow that store is trying to read data from your MySQL database and it is not valid JSON. I would suggest opening this issue in the store module https://github.com/chill117/express-mysql-session for further assistance.

**Comment by 0zob** [comment]
Thank you very much for the reply, I already published the issue in express-mysql-session.
