### ISSUE TITLE
server crash on fetch request from the client.

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [expressjs/session#897]
using the firefox debugger i coppied the whole request

```await fetch("http://localhost:8000/event/", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0",
        "Accept": "*/*",
        "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
        "Content-Type": "multipart/form-data; boundary=---------------------------69717508338214717692318237243",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin"
    },
    "referrer": "http://localhost:8000/",
    "body": "-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"name\"\r\n\r\nbite\r\n-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"type\"\r\n\r\nTD\r\n-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"description\"\r\n\r\nfd\r\n-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"teacher\"\r\n\r\nfd\r\n-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"dateStart\"\r\n\r\n2022-05-31T23:00:00.000Z\r\n-----------------------------69717508338214717692318237243\r\nContent-Disposition: form-data; name=\"dateEnd\"\r\n\r\n2022-06-01T03:00:00.000Z\r\n-----------------------------69717508338214717692318237243--\r\n",
    "method": "POST",
    "mode": "cors"
});
```
this request causes this in the backend

```
ode:_http_outgoing:791
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at new NodeError (node:internal/errors:377:5)
    at write_ (node:_http_outgoing:791:11)
    at ServerResponse.end (node:_http_outgoing:923:5)
    at writeend (/home/marc/ProjectsQueJeFiniraisPas/projetWeb/node_modules/express-session/index.js:262:22)
    at Immediate.ontouch (/home/marc/ProjectsQueJeFiniraisPas/projetWeb/node_modules/express-session/index.js:353:11)
    at process.processImmediate (node:internal/timers:471:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Thrown at:
    at __node_internal_captureLargerStackTrace (node:internal/errors:466:5)
    at NodeError (node:internal/errors:377:5)
    at write_ (node:_http_outgoing:791:11)
    at end (node:_http_outgoing:923:5)
    at writeend (/home/marc/ProjectsQueJeFiniraisPas/projetWeb/node_modules/express-session/index.js:262:22)
    at ontouch (/home/marc/ProjectsQueJeFiniraisPas/projetWeb/node_modules/express-session/index.js:353:11)
    at processImmediate (node:internal/timers:471:21)

Node.js v18.3.0
```

**Comment by Marc-Pierre-Barbier** [comment]
Ok i was dumb the cause wasn't the request but the parameter of res.end() i gave garbage to this function with lead to the crash

**Comment by dougwilson** [comment]
Hi, and thanks for the report. Unfortunately this module just calls res.write/res.end with what your code called it with. It seems it was called with an Object according to Node.js.

This module being in the stack trace is generally a red hearing for that error. We can look into the issue if you have what was called in that case, though

**Comment by Marc-Pierre-Barbier** [comment]
we sent our message almost at the same tame. like i just message the cause wasn't express-session i just fed and object to res.end with was a mistake. im sorry to have wasted your time.
