### ISSUE TITLE
Invalid argument type express-session "1.17.3" and redis "4.6.7",

### ISSUE THREAD

**Issue by cesco69** [expressjs/session#944]
```
TypeError: Invalid argument type
    at encodeCommand (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\RESP2\encoder.js:17:19)
    at RedisCommandsQueue.getCommandToSend (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\commands-queue.js:138:45)
    at Commander._RedisClient_tick (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\index.js:515:76)
    at Commander._RedisClient_sendCommand (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\index.js:502:82)
    at Commander._RedisClient_legacySendCommand (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\index.js:456:105)
    at Commander.sendCommand (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\index.js:428:114)
    at <computed> [as set] (backend\node_modules\.pnpm\@redis+client@1.5.8\node_modules\@redis\client\dist\lib\client\index.js:474:27)
    at Object.set (backend\node_modules\.pnpm\connect-redis@7.1.0_express-session@1.17.3\node_modules\connect-redis\dist\cjs\index.js:24:34)
    at RedisStore.set (backend\node_modules\.pnpm\connect-redis@7.1.0_express-session@1.17.3\node_modules\connect-redis\dist\cjs\index.js:71:39)
    at Session.save (backend\node_modules\.pnpm\express-session@1.17.3\node_modules\express-session\session\session.js:72:25)
```
package.json
```
{
    "@socket.io/redis-adapter": "^8.2.1",
    "acca-srv-prodotti-client": "^4.0.3",
    "agentkeepalive": "^4.3.0",
    "aws-sdk": "^2.1402.0",
    "axios": "^1.4.0",
    "bee": "^0.1.1",
    "bee-queue": "^1.4.0",
    "body-parser": "^1.20.2",
    "bottleneck": "^2.19.5",
    "bull-arena": "^3.30.4",
    "busboy": "^1.6.0",
    "compression": "^1.7.3",
    "connect-redis": "^7.1.0",
    "cookie-parser": "^1.4.6",
    "copyfiles": "^2.4.1",
    "cors": "^2.8.4",
    "del": "^7.0.0",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "express-socket.io-session": "^1.3.5",
    "fast-xml-parser": "^4.2.4",
    "html-entities": "^2.3.6",
    "iconv-lite": "^0.6.3",
    "jsdom": "^22.1.0",
    "jsonwebtoken": "^9.0.0",
    "moment": "^2.29.4",
    "mongodb": "^5.6.0",
    "mustache": "^4.2.0",
    "nodemailer": "^6.9.3",
    "proxy-agent": "^6.2.1",
    "qs": "^6.11.2",
    "queue": "^7.0.0",
    "redis": "^4.6.7",
    "response-time": "^2.3.2",
    "sax": "^1.2.4",
    "socket.io": "^4.7.0",
    "socket.io-client": "^4.7.0",
    "tslib": "^2.5.3",
    "usbim-sdk-api": "^1.1.17",
    "usbim-sdk-backend": "^2.1.29",
    "usbim-sdk-common": "^2.1.35",
    "uuid": "^9.0.0"
  }
```

**Comment by dougwilson** [comment]
Hello, and sorry you are having trouble. Unfortunately whatever the issue is is likely disconnected from this module, as the store interface is standard between all stores and is just a plain object. You probably want to open this with your store, `connect-redis`.
