### ISSUE TITLE
Cookie session not working with passportJS

### ISSUE THREAD

**Issue by EjiroOsiephri** [expressjs/session#967]
While the express js session i s working perfectly with the oauth flow created by passportJS, the cookie session is having a bug stating req.session.regenerate this is the error code TypeError: req.session.regenerate is not a function
    at SessionManager.logIn (C:\Users\User\Documents\node js\security-auth\node_modules\passport\lib\sessionmanager.js:28:15)
    at req.login.req.logIn (C:\Users\User\Documents\node js\security-auth\node_modules\passport\lib\http\request.js:39:26)
    at strategy.success (C:\Users\User\Documents\node js\security-auth\node_modules\passport\lib\middleware\authenticate.js:265:13)
    at verified (C:\Users\User\Documents\node js\security-auth\node_modules\passport-oauth2\lib\strategy.js:189:20)
    at Strategy.verifyCallback [as _verify] (C:\Users\User\Documents\node js\security-auth\server.js:42:3)
    at C:\Users\User\Documents\node js\security-auth\node_modules\passport-oauth2\lib\strategy.js:205:24
    at C:\Users\User\Documents\node js\security-auth\node_modules\passport-google-oauth20\lib\strategy.js:122:5
    at passBackControl (C:\Users\User\Documents\node js\security-auth\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\User\Documents\node js\security-auth\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)

**Comment by joewagner** [comment]
Hi @EjiroOsiephri 
It's hard to say for sure what is causing your issue.  If it's possible for you to share a runnable application that reproduces the problem, that would make it easier for someone to help you.

**Comment by Ajlanclos** [comment]
I'm having a similar issue after updating chrome to latest.
