### ISSUE TITLE
express session is failing because session is undefined

### ISSUE THREAD

**Issue by nikitakogan1994** [expressjs/session#980]
Hi,

I am working with expressjs session as part of my application. 
Sometimes, when a logout occurs, the code is trying to reload the session which is 'undefined' by then.

Is it possible to have a fix to check if the session is not 'undefined'? the failure is coming from the express-session code. (index.js line 387) It causes the crash of our application...

**stack trace:**
Exit status 1
      var _reload = sess.reload
    at /home/vcap/app/node_modules/express-session/index.js:387:11
                         ^
    at /home/vcap/app/node_modules/express-session/session/session.js:94:23
**TypeError: Cannot read properties of undefined (reading 'reload')**
    at /home/vcap/app/node_modules/@sap/approuter/lib/backend-request/memstore.js:134:59
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/home/vcap/app/node_modules/express-session/index.js:381
    at wrapmethods (/home/vcap/app/node_modules/express-session/index.js:381:26)
    at /home/vcap/app/node_modules/@sap/approuter/lib/backend-request/memstore.js:262:5
Node.js v18.17.1

**Comment by UlisesGascon** [comment]
Hey @nikitakogan1994! Thanks for reporting this error... can you provide some code about the bug so we can reproduce it?

**Comment by rage28** [comment]
We are also facing the same issue. Will try to get more info and post here

**Comment by bjohansebas** [comment]
Closing since no further information was provided. Feel free to provide more details and I will reopen it.
